### ISSUE TITLE
Use the W3C - CG template

### ISSUE THREAD

**Issue by dachafra** [kg-construct/rml-star#1]
https://www.w3.org/community/reports/reqs/

**Comment by ghost** [comment]
In commit 3d9debdb5fb1942481eb9399835ca6e49329c073 the ReSpec template we used for the target spec was added. I'll still verify whether this conforms to the W3 link above and then this issue can be closed.

**Comment by dachafra** [comment]
do we want to add w3c and CG pictures as we did in other specs? @andimou  (e.g., https://rml.io/r2rml-implementation-report) or should we use the current template for this first version?
