### ISSUE TITLE
Examples of the Syntax of RML-Star

### ISSUE THREAD

**Issue by eiglesias34** [kg-construct/rml-star#10]
Hello,

I have noticed some things in the examples that I would like to bring to your attention. First, two examples use the `rr:datatype xsd:float` clause but the results don't reflect it; in other words, `^^xsd:float` does not appear as part of the resulting triples. This can confuse those who only use the examples as a guide. Second, there is no example where `rml:quotedTriplesMap` is used as an `objectMap`. Finally, I noticed that prefix for `subjectMap` and `objectMap` has been changed from `rr` to `rml`. My issue was that there is no indication (at least from my understanding) in the text about this change. When I saw `subjectMaps` and `objectMaps` with `rml` prefix in the examples, I did not know if that was a mistake.

Sincerely,
Enrique Iglesias

**Comment by dachafra** [comment]
Thanks @eiglesias34.
@anaigmo if you prefer, you can open a specific issue for each problem provided here.

**Comment by anaigmo** [comment]
Thanks for the feedback @eiglesias34 !
The new release includes fixes to what you. mention, section 2.1 now highlights the prefix change, but if you think it could be said elsewhere just let me know :)
