### ISSUE TITLE
Testcases: add tests

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-star#17]
Testcases are here: https://github.com/kg-construct/rml-star-test-cases

- Do they cover the current spec?
- Do they include invalid cases, thus throwing errors?

Useful for validating the SHACL shapes and make sure we cover everything

**Comment by anaigmo** [comment]
They would need to be updated regarding the IRI namespace and prefix, to have everything with `rml:`, otherwise I think there are no more changes in this spec. They don't include invalid test cases though, @dachafra please confirm

**Comment by dachafra** [comment]
I confirm that there are no invalid test cases. Do we need them? @DylanVanAssche 

Considering the way other specs are structured, should we incorporate the test-cases in this repo? @anaigmo

**Comment by anaigmo** [comment]
yeah I think it makes sense

**Comment by DylanVanAssche** [comment]
> I confirm that there are no invalid test cases. Do we need them

Without them the shapes are very hard to verify if they cover all possible cases @dachafra 

> Considering the way other specs are structured, should we incorporate the test-cases in this repo? @anaigmo

I have them indeed in rml-io, next to the shapes. Both are connected, if you change a test-case you need to make sure it doesn't violate any shape and if you change the spec, you may need to update a shape and/or test-case.

**Comment by dachafra** [comment]
I've found a set of RDF-star test cases for checking invalid syntax, we can transform and add them:
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-1
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-2
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-3
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-4
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-5
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-6
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-7
- https://w3c.github.io/rdf-star/tests/turtle/syntax/#turtle-star-bad-8

**Comment by DylanVanAssche** [comment]
Would be nice to have them, not sure the engines can generate these? At least they do not impact the mappings I think?

**Comment by dachafra** [comment]
Nop, they are mainly for data. So, the engines would be the ones who will output these errors. I think we can leave it for now for shapes, and once we have a final structure we can also add these new ones.
