### ISSUE TITLE
Documentation minor issues

### ISSUE THREAD

**Issue by frmichel** [kg-construct/rml-star#18]
Here are minor issues to update in the dev.html, that I saw while updating the rml-cc spec:
- `issueBase: https://github.com/kg-construct/rml-star-spec/issues` : remove the "-spec"
- "https://rml.io/" to change with w3id-based url
- copyrightStart: "2021": update year
- namespace definition: rml: http://semweb.mmlab.be/ns/rml#

**Comment by anaigmo** [comment]
fixed now, thanks @frmichel !
