### ISSUE TITLE
Link from spec to github

### ISSUE THREAD

**Issue by bblfish** [kg-construct/rml-star#9]
with the original RML spec I could not find the link from the spec to the github. It took a lot of questions for people pointing me from one to the other before I found out where to ask questions. This spec is better as it points to github.io which allows one to guess what the link is. But guesses are not as good as links. Also if someone came to this repo they would have to guess where the spec was located, making it more difficult to send feeback.
See https://github.com/kg-construct/rml-questions/issues/23#issuecomment-1188732643

**Comment by dachafra** [comment]
In this specific repo, we have the direct link to the spec. To be honest I don't think we need to do more in this way. @anaigmo would be possible to add a link to the GitHub repo in the spec web?
<img width="346" alt="image" src="https://user-images.githubusercontent.com/12400271/179768008-cb443de9-7bea-42fe-adb6-079ac065b7ce.png">

**Comment by anaigmo** [comment]
Sure, I will add it for the next release

**Comment by VladimirAlexiev** [comment]
@anaigmo Can you also add a link to "issues"? Many W3 specs have such link.

**Comment by anaigmo** [comment]
Done, the new release now includes the link to github, issues and pull requests :) Thanks for the feedback!
